apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-lightblue-deployment
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: "rocketronald/lightbluecompute-catalog:latest"
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 60
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Pass4Admin123"
        - name: MYSQL_USER
          value: "dbuser"
        - name: MYSQL_PASSWORD
          value: "Pass4dbUs3R"
        - name: MYSQL_DATABASE
          value: "inventorydb"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-lightblue-service
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  ports:
   - port: 8081
     targetPort: 8081
