apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
# This requires the simple pipeline tasks from the pipeline hotel to be installed first
# and the simple pipeline, and the conditional resource
metadata:
  name: bluecompute-build-and-deploy-pipeline-inventory-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: bluecompute-inventory-pr-
      namespace: light-bc
    spec:
      pipelineRef:
        name: bluecompute-build-and-deploy-pipeline-inventory
      resources:
        - name: git-source-inventory
          resourceRef:
            name: git-source-inventory
        - name: docker-image-inventory
          resourceRef:
            name: docker-image-inventory
      params:
        - name: pathToYamlFile
          value: "k8s_yamls"
        - name: pathToDeployableFile
          value: "k8s_yamls_mcm"
      serviceAccountName: pipeline-account
      timeout: "1h0m0s"
